site_name: Hacktoberfest in Ado-Ekiti
site_description: OpenSource with DSC EKSU, ækiti æmbassy, Superhero, and Hacktoberfest
site_author: Emmanuel Joseph(JET)
repo_name: 'emmanuelJet/HFA-Doc'
repo_url: 'https://github.com/emmanuelJet/HFA-Doc'
nav:
  - Welcome: 'index.md'
  - Meetup:
    - One Hour with GitHub: 'meetup/one-hour-with-github.md'
    - OpenSource with æternity: 'meetup/opensource-with-aeternity.md'
  - Tagging: 'tagging.md'
  - Agenda: 
    - One Hour with GitHub: 'agenda/one-hour-with-github.md'
    - OpenSource with æternity: 'agenda/opensource-with-aeternity.md'
  - Guildlines:
    - Hacktoberfest: 'guildlines/hacktoberfest.md'
    - DSC EKSU: 'guildlines/dsceksu.md'
    - ækiti: 'guildlines/aekiti.md'
    - Documentation: 'guildlines/documentation.md'
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: pink
    accent: black
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: https://aekiti.com/favicon.ico
  icon:
    logo: fontawesome/brands/readme
    repo: fontawesome/brands/git-alt
  features:
    - header.autohide
    - search.highlight
google_analytics:
  - UA-152643946-2
  - auto
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
extra:
  logo: https://aekiti.github.io/hacktoberfest2020/assets/images/hfa_512x512.jpg
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/channel/UCISZ6H0Zb-ndRLSgcR1sH_g
    - icon: fontawesome/brands/telegram
      link: https://telegram.me/aekiti